Django/categorias/urls.py
from django.urls import path
from . import views

app_name = "categorias"

urlpatterns = [
    path('', views.index, name="index"),
    path("formulario", views.formulario, name='formulario'),
    path('<int:categoria_id>', views.detalle_categoria, name="detalle"),
    path('edit/<int:categoria_id>', views.editar_categoria, name="editar"),
    path('delete/<int:categoria_id>', views.eliminar_categoria, name="eliminar")
]

Django/primerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path("categorias/", include("categorias.urls"))
]

Django/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('', views.index, name="index"),
    path("formulario", views.formulario, name='formulario'),
    path('<int:producto_id>', views.detalle, name="detalle"),
    path('edit/<int:producto_id>', views.editar_producto, name="editar"),
    path('delete/<int:producto_id>', views.eliminar_producto, name="eliminar")
]

Django/categorias/models.py
from django.db import models

# Create your models here.

Django/productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.nombre

    # CASCADE: eliminar el Producto
    # PROTECT: lanza un error
    # RESTRICT: solo elimina si no existen productos
    # SET_NULL: actualiza a valor nulo
    # SET_DEFAULT: asigna valor por defecto

Django/productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']


class CategoriaForm(ModelForm):
    class Meta:
        model = models.Categoria
        fields = ["nombre"]

Django/categorias/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from productos.forms import CategoriaForm, ProductoForm
from productos.models import Categoria

# Create your views here.


def index(request):
    categorias = Categoria.objects.all().values()
    print(categorias)
    return render(
        request,
        'index_categorias.html',
        context={'categorias': categorias}
    )

# agregar producto


def formulario(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/categorias")
    else:
        form = CategoriaForm()

    return render(
        request,
        'formulario_categoria.html',
        {'form': form}
    )

# get


def detalle_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id=categoria_id)
    return render(request, "detalle_categoria.html", context={'categoria': categoria})


# editar producto


def editar_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id=categoria_id)
    if request.method == "POST":
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/categorias")
    else:
        form = CategoriaForm(instance=categoria)
    return render(
        request,
        'editar_categoria.html',
        {'form': form}
    )

# eliminar producto


def eliminar_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id=categoria_id)
    if request.method == 'POST':
        categoria.delete()
        return HttpResponseRedirect("/categorias")
    return render(request, 'eliminar_categoria.html', {'categoria': categoria})

Django/primerProyecto/views.py
from django.shortcuts import render


def inicio(request):
    return render(
        request,
        'inicio.html'
    )

Django/productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render

from productos.forms import ProductoForm
from .models import Producto

# Create your views here.

# productos


def index(request):
    productos = Producto.objects.all().values()
    return render(
        request,
        'index.html',
        context={'productos': productos}
    )


def detalle(request, producto_id):
    # Otra manera de manejar elemento inexsistente
    producto = get_object_or_404(Producto, id=producto_id)
    return render(request, "detalle.html", context={'producto': producto})

# agregar producto


def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos")
    else:
        form = ProductoForm()

    return render(
        request,
        'producto_form.html',
        {'form': form}
    )

# editar producto


def editar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos")
    else:
        form = ProductoForm(instance=producto)
    return render(
        request,
        'producto_editar.html',
        {'form': form}
    )

# eliminar producto


def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    if request.method == 'POST':
        producto.delete()
        return HttpResponseRedirect("/productos")
    return render(request, 'producto_eliminar.html', {'producto': producto})
    # Manejar error cuando no exista un elemento
    # try:
    #     producto = Producto.objects.get(id=producto_id)
    #     return render(request, "detalle.html", context={'producto': producto})
    # except Producto.DoesNotExist:
    #     raise Http404()

    # agregar values y usar la clase JsonResponse para devolver los datos en Json
    # convertir a lista los elementos y agregar safe=False

    # productos = Producto.objects.all().values()
    # return JsonResponse(list(productos), safe=False)

    # para mostrar los productos con puntaje igual o mayor "filter"
    # productos = Producto.objects.filter(puntaje=3)

    # para buscar elemenento en especifico se puede enviar el id o el pk (primary key)
    # productos = Producto.objects.get(id=1)

Django/categorias/templates/detalle_categoria.html
{% extends 'base.html' %} {% block content %}

<article>
    <div class="m-2">
        <strong>
            <h4>Nombre</h4>
        </strong>
        <p>{{categoria.nombre}}</p>
    </div>
</article>
<a class="btn btn-primary" href="/categorias">Regresar</a>

{% endblock %}

Django/categorias/templates/editar_categoria.html
{% extends 'base.html' %} {% block content %}

<form novalidate method="POST">
    {% csrf_token %} {{form}}
    <section class="mb-3 d-flex justify-content-end gap-3">
        <a href="/categorias" class="btn btn-danger">Cancelar</a>
        <input class="btn btn-primary" type="submit" value="Guardar" />
    </section>
</form>

{% endblock %}

Django/categorias/templates/eliminar_categoria.html
{% extends 'base.html' %} {% block content %}

<h1>Confirmar</h1>
<h3>¿Deseas eliminar la categoría {{categoria.nombre}}? </h3>
<form method="POST">
    {% csrf_token %}
    <div class="mt-3 d-flex justify-content-end gap-1">
        <a href="/categorias" class="btn btn-danger">Cancelar</a>
        <input class="btn btn-primary" type="submit" value="Si" />
    </div>
</form>

{% endblock %}

Django/categorias/templates/formulario_categoria.html
{% extends 'base.html' %} {% block content %}

<form novalidate action="{% url 'categorias:formulario' %}" method="POST">
    {% csrf_token %} {{form}}
    <section class="mt-3 d-flex justify-content-end gap-3">
        <a class="btn btn-danger" href="/categorias">Cancelar</a>
        <input class="btn btn-primary" type="submit" value="Guardar" />
    </section>
</form>

{% endblock %}

Django/categorias/templates/index_categorias.html
{% extends 'base.html' %} {% block content %}

<h1>Categorías</h1>

<section class="d-flex justify-content-end">
    <a class="btn btn-success" href="{% url "categorias:formulario" %}">
        Nueva categoría
    </a>
</section>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for categoria in categorias %}
        <tr>
            <td>{{categoria.nombre}}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'categorias:detalle' categoria.id %}">
                    Ver detalle
                </a>
                <a class="btn btn-warning" href="{% url 'categorias:editar' categoria.id %}">
                    Editar
                </a>
                <a class="btn btn-danger" href="{% url 'categorias:eliminar' categoria.id %}">
                    Eliminar
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Django/productos/templates/detalle.html
{% extends 'base.html' %} {% block content %}

<article>
  <div class="m-2">
    <strong>
      <h4>Nombre</h4>
    </strong>
    <p>{{producto.nombre}}</p>
  </div>
  <div class="m-2">
    <strong>
      <h4>Stock</h4>
    </strong>
    <p>{{producto.puntaje}}</p>
  </div>
  <div class="m-2">
    <strong>
      <h4>Puntaje</h4>
    </strong>
    <p>{{producto.puntaje}}</p>
  </div>
  <div class="m-2">
    <strong>
      <h4>Categoría</h4>
    </strong>
    <p>{{producto.categoria}}</p>
  </div>
  <div class="m-2">
    <strong>
      <h4>Fecha creación</h4>
    </strong>
    <p>{{producto.create_date}}</p>
  </div>
</article>
<a class="btn btn-primary" href="/productos">Regresar</a>

{% endblock %}

Django/productos/templates/index.html
{% extends 'base.html' %} {% block content %}

<h1>Productos</h1>

<section class="d-flex justify-content-end">
  <a class="btn btn-success" href="{% url "productos:formulario" %}">
    Nuevo producto
  </a>
</section>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Stock</th>
      <th>Puntaje</th>
      {% comment %} <th>Categoría</th> {% endcomment %}
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
    <tr>
      <td>{{producto.nombre}}</td>
      <td>{{producto.stock}}</td>
      <td>{{producto.puntaje}}</td>
      {% comment %} <td>{{producto.categoria}}</td> {% endcomment %}
      <td>
        <a class="btn btn-primary" href="{% url 'productos:detalle' producto.id %}">
          Ver detalle
        </a>
        <a class="btn btn-warning" href="{% url 'productos:editar' producto.id %}">
          Editar
        </a>
        <a class="btn btn-danger" href="{% url 'productos:eliminar' producto.id %}">
          Eliminar
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

Django/productos/templates/producto_editar.html
{% extends 'base.html' %} {% block content %}

<form novalidate method="POST">
    {% csrf_token %} {{form}}
    <section class="mb-3 d-flex justify-content-end gap-3">
        <a href="/productos" class="btn btn-danger">Cancelar</a>
        <input class="btn btn-primary" type="submit" value="Guardar" />
    </section>
</form>

{% endblock %}

Django/productos/templates/producto_eliminar.html
{% extends 'base.html' %} {% block content %}

<h1>Confirmar</h1>
<h3>¿Deseas eliminar el producto {{producto.nombre}}? </h3>
<form method="POST">
    {% csrf_token %}
    <div class="mt-3 d-flex justify-content-end gap-1">
        <a href="/productos" class="btn btn-danger">Cancelar</a>
        <input class="btn btn-primary" type="submit" value="Si" />
    </div>
</form>

{% endblock %}

Django/productos/templates/producto_form.html
{% extends 'base.html' %} {% block content %}

<form novalidate action="{% url 'productos:formulario' %}" method="POST">
  {% csrf_token %} {{form}}
  <section class="mt-3 d-flex justify-content-end gap-3">
    <a class="btn btn-danger" href="/productos">Cancelar</a>
    <input class="btn btn-primary" type="submit" value="Guardar" />
  </section>
</form>

{% endblock %}

Django/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Productly</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
  </script>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-success">
    <div class="container-fluid">
      <a class="navbar-brand text-white" href="">Django</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href="{% url "inicio" %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url "productos:index" %}">Productos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url "categorias:index" %}">Categorías</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <section class="container mt-2">{% block content %} {% endblock %}</section>
</body>

</html>

Django/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>
{% else %}{{ label }}{% endif %}

Django/templates/django/forms/widgets/input.html
<input class="form-control {{widget.attrs.class}}" type="{{ widget.type }}" name="{{ widget.name }}"
    {% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}" {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

Django/templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"
    {% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
        {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

Django/templates/form_snippets.html
{% load add_attr %}

{% for field in form %}
<section class="mb-3">
    {{ field.label_tag }}
    {% if field.errors %}
    {{field|add_attr:"class:is-invalid"}}
    {% else %}
    {{field}}
    {% endif %}
    <div class="invalid-feedback">
        {% for error in field.errors %}
        {{error}}
        {% endfor %}
    </div>
</section>
{% endfor %}

Django/templates/inicio.html
{% extends "base.html" %}

{% block content %}
Gestor de productos
{% endblock content %}